influxdb:
  hostname: "influxdb"
  port: "8086"
  database: "easy_influx"
  insert_interval: "30"

esxi_hosts:
  - hostname: "192.168.100.10"
    snmp_community: "public"
    snmp_version: "2c"

sw1:
  - hostname: "192.168.100.2"
    snmp_community: "public"
    snmp_version: "2c"
