version: "3.5"

networks:
  influx:
  zabbix:

volumes:
  grafana-storage:

services:
  influxdb:
    container_name: influxdb
    image: influxdb
    networks:
      - influx
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb:/var/lib/influxdb
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - influx
    environment:
      - "GF_SECURITY_ADMIN_PASSWORD=admin"
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: always

  telegraf:
    container_name: telegraf
    image: telegraf
    networks:
      - influx
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - ./telegraf/conf:/etc/telegraf/telegraf.d
      - /var/run/docker.sock:/var/run/docker.sock
      - ./mibs:/usr/share/snmp/mibs
    restart: always

zabbix-mysql-server:
  container_name: zabbix-mysql-server
  image: mysql:5.6
  restart: always
  image: mysql:5.6
  volumes:
    - ./zabbid_db:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD="root_pwd"
    - MYSQL_DATABASE="zabbix-mysql-server"
    - MYSQL_USER="zabbix"
    - MYSQL_PASSWORD="password"

zabbix-server:
  container_name: zabbix-server
  image: zabbix/zabbix-server-mysql
  restart: always
  networks:
    - zabbix
  depends_on:
    - zabbix-mysql-server
  volumes:
    - zabbix:/usr/lib/zabbix
  environment:
    - DB_SERVER_HOST="http://zabbix-mysql-server"
    - MYSQL_DATABASE="zabbix"
    - MYSQL_USER="zabbix"
    - MYSQL_PASSWORD="password"
    - MYSQL_ROOT_PASSWORD="root_pwd"
    - ZBX_HISTORYSTORAGETYPES=log,text
    - ZBX_DEBUGLEVEL=1
    - ZBX_HOUSEKEEPINGFREQUENCY=1
    - ZBX_MAXHOUSEKEEPERDELETE=5000

zabbix-web:
  image: zabbix/zabbix-web-nginx-mysql
  restart: always
  environment:
    - DB_SERVER_HOST="http://zabbix-mysql-server"
    - MYSQL_DATABASE="zabbix"
    - MYSQL_USER="zabbix"
    - MYSQL_PASSWORD="password"
    - ZBX_SERVER_HOST=zabbix-server
    - ZBX_POSTMAXSIZE=64M
    - PHP_TZ="Australia/Adelaide"
    - ZBX_MAXEXECUTIONTIME: 500
  depends_on:
    - zabbix-mysql-server
    - zabbix-server
  ports:
    - 8090:80

zabbix-agent:
  image: zabbix/zabbix-agent:latest
  privileged: true
  network_mode: "host"
  restart: unless-stopped
  environment:
    - ZBX_SERVER_HOST=zabbix-server
