version: "3.5"

networks:
  influx:
    external:
      name: influx
  traefik:
    external:
      name: traefik

volumes:
  grafana-storage:

services:

  zabbix-appliance:
    container_name: zabbix
    image: zabbix/zabbix-appliance
    networks:
      - influx
      - traefik
    restart: always
    ports:
      - "10051:10051"
    volumes:
      - ./mibs:/var/lib/zabbix/mibs
      - ./zabbix/db:/var/lib/mysql
      - ./zabbix:/usr/lib/zabbix
    environment:
      - ZBX_DEBUGLEVEL=1
      - ZBX_HOUSEKEEPINGFREQUENCY=1
      - ZBX_MAXHOUSEKEEPERDELETE=5000
      - ZBX_POSTMAXSIZE=64M
      - PHP_TZ="Australia/Adelaide"
      - ZBX_MAXEXECUTIONTIME=500
      - ZBX_SERVER_NAME="Zabbix Cornerstone"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=zabbix"
      - "traefik.frontend.rule=Host:zabbix.cornerstone.sa.edu.au"
      - "traefik.docker.network=traefik"
